# Generated by Django 5.0.3 on 2024-04-22 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(blank=True, max_length=100, null=True)),
                ('subject_code', models.CharField(blank=True, max_length=100, null=True)),
                ('decription', models.TextField(blank=True, null=True)),
                ('paid', models.BooleanField(blank=True, null=True)),
            ],
        ),
    ]
