# Generated by Django 5.0.3 on 2024-04-22 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_courses_paid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courses',
            old_name='decription',
            new_name='description',
        ),
    ]
