# Generated by Django 5.0.3 on 2024-04-22 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_rename_decription_courses_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='paid',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
