# Generated by Django 5.0.3 on 2024-05-16 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_rename_subject_courses_subjectname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='subjectname',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.subject'),
        ),
    ]
