# Generated by Django 5.0.3 on 2024-06-05 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_alter_classes_courses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classes',
            name='courses',
            field=models.ForeignKey(default=' ', on_delete=django.db.models.deletion.CASCADE, to='home.subject'),
        ),
    ]
