# Generated by Django 5.0.3 on 2024-04-22 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='paid',
            field=models.BooleanField(blank=True, default='no', null=True),
        ),
    ]
