# Generated by Django 5.0.3 on 2024-05-15 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_captcha'),
    ]

    operations = [
        migrations.DeleteModel(
            name='captcha',
        ),
    ]
