# Generated by Django 5.0.3 on 2024-05-16 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_subject_remove_courses_subject_code_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courses',
            old_name='subject',
            new_name='subjectname',
        ),
    ]
