# Generated by Django 5.0.3 on 2024-05-17 07:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_alter_courses_subjectname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classes',
            name='courses',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.subject'),
        ),
    ]
