# Generated by Django 5.0.3 on 2024-06-05 13:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_alter_classes_courses'),
    ]

    operations = [
        migrations.AddField(
            model_name='classes',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='classes',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='class_video', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['MOV', 'mp4', 'webm', 'avi', 'mkv'])]),
        ),
    ]
