# Generated by Django 5.0.3 on 2024-06-05 14:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_alter_classes_courses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classes',
            name='courses',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.subject'),
        ),
        migrations.AlterField(
            model_name='courses',
            name='subjectname',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.subject'),
        ),
    ]
