# Generated by Django 5.0.6 on 2024-06-12 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_alter_classes_thumbnail_alter_classes_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='notes',
            field=models.FileField(blank=True, null=True, upload_to='notes/'),
        ),
    ]
