# Generated by Django 5.0.6 on 2024-06-12 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_courses_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='notes',
            field=models.FileField(blank=True, default=None, null=True, upload_to='notes/'),
        ),
    ]
