# Generated by Django 5.0.6 on 2024-06-14 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0030_blogstory_story_pic_blogstory_upload_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogstory',
            name='story',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
